-- @operation: export
-- @entity: batch
-- @name: Updated Anime LQ/Raws Regex
-- @exportedAt: 2026-06-30T21:30:49.644Z
-- @opIds: 2427, 2428

-- --- BEGIN op 2427 ( update regular_expression "Anime LQ" )
update "regular_expressions" set "pattern" = '(?i)(?:^\[|(?<=-)|(?<=\[))(?:$tore-Chill|0neshot|224|A-Destiny|AceAres|AhmadDev|Anime[ .-]?Chap|Anime[ .-]?Land|Anime[ .-]?Time|AnimeDynastyEN|AnimeKuro|AnimeRG|Animesubs|AnimeTR|Anitsu|AniVoid|ArataEnc|AREY|Ari|ASW|(?:Baked|Dead|Space)Fish|BJX|BlackLuster|bonkai77|CameEsp|Cat66|CBB|Cerberus|Cleo|CuaP|DaddySubs|DARKFLiX|DB|DBArabic|Deadmau[ .-]?RAWS|DKB|DP|DsunS|Emmid|ExREN|FAV|FunArts|GERMini|Hakata[ .-]?Ramen|Hall_of_C|Hatsuyuki|HAV1T|HENiL|Hitoku|HollowRoxas|HR|ICEBLUE|iPUNISHER|JacobSwaggedUp|Johnny-englishsubs|Kallango|Kanjouteki|KEKMASTERS|Kirion|KQRM|KRP|LoliHouse|M@nI|mal[ .-]?lu[ .-]?zen|Man\.K|Maximus|MD|mdcx|Metaljerk|MGD|MiniFreeza|MinisCuba|MiniMTBB|MiniTheatre|Mites|Modders[ .-]?Bay|Mr\.Deadpool|N[eo][wo]b[ ._-]?Subs|NemDiggers|neoHEVC|Nokou|NS|Nyanpasu|OldCastle|Pantsu|Pao|phazer11|Pixel|Plex[ .-]?Friendly|PnPSubs|Polarwindz|Project-gxs|PuyaSubs|QAS|QCE|Rando235|Ranger|Rapta|Raze|Reaktor|RightShiftBy2|Rip[ .-]?Time|SAD|Salieri|Samir755|SanKyuu|SEiN|sekkusu&ok|SHFS|shincaps|SLAX|Sokudo|SRW|SSA|StrayGods|Suki[ .-]?Desu|TeamTurquoize|Tenrai[ .-]?Sensei|TnF|TOPKEK|Trix|U3-Web|UNBIASED|uP|USD|Valenciano|VipapkStudios|Wardevil|WtF[ ._-]?Anime|xiao-av1|Yabai_Desu_NeRandomRemux|YakuboEncodes|youshikibi|YuiSubs|Yun|zza)(?:\]|\b|$)' where "name" = 'Anime LQ' and "pattern" = '(?i)(?:^\[|(?<=-)|(?<=\[))(?:\$tore-Chill|0neshot|224|A-Destiny|AceAres|AhmadDev|Anime[._ ]Chap|Anime[._ ]Land|Anime[._ ]Time|AnimeDynastyEN|AnimeKuro|AnimeRG|Animesubs|AnimeTR|Anitsu|AniVoid|ArataEnc|AREY|Ari|ASW|BJX|BlackLuster|bonkai77|CameEsp|Cat66|CBB|Cerberus|Cleo|CuaP|DaddySubs|DARKFLiX|DB|DBArabic|Deadmau-RAWS|DKB|DP|DsunS|Emmid|ExREN|FAV|Fish|FunArts|GERMini|Hakata[._ ]Ramen|Hall_of_C|Hatsuyuki|HAV1T|HENiL|Hitoku|HollowRoxas|HR|ICEBLUE|iPUNISHER|JacobSwaggedUp|Johnny-englishsubs|Kallango|Kanjouteki|KEKMASTERS|Kirion|KQRM|KRP|LoliHouse|M@nI|Man\.K|Maximus|MD|mdcx|Metaljerk|MGD|MiniFreeza|MinisCuba|MiniMTBB|MiniTheatre|Mites|Modders[._ ]Bay|Mr\.[._ ]Deadpool|NemDiggers|neoHEVC|Nokou|NoobSubs|NS|Nyanpasu|OldCastle|Pantsu|Pao|phazer11|Pixel|Plex[._ ]Friendly|PnPSubs|Polarwindz|Project-gxs|PuyaSubs|QaS|QCE|Rando235|Ranger|Rapta|Raw[._ ]Files|Raze|Reaktor|RightShiftBy2|Rip[._ ]Time|SAD|Salieri|Samir755|SanKyuu|SEiN|sekkusu&ok|SHFS|shincaps|SLAX|Sokudo|SRW|SSA|StrayGods|Suki[._ ]Desu|TeamTurquoize|Tenrai[._ ]Sensei|TnF|TOPKEK|Trix|U3-Web|UNBIASED|uP|USD|Valenciano|VipapkStudios|Wardevil|WtF[._ ]Anime|xiao-av1|Yabai_Desu_NeRandomRemux|YakuboEncodes|youshikibi|YuiSubs|Yun|zza)(?:\]|\b|$)';
-- --- END op 2427

-- --- BEGIN op 2428 ( update regular_expression "Anime Raws" )
update "regular_expressions" set "pattern" = '(?i)(?:^\[|(?<=-)|(?<=\[))(?:Asuka[ ._-]?Raws|Beatrice[ ._-]?Raws|Daddy[ ._-]?Raws|Fumi[ ._-]?Raws|Iriza[ ._-]?Raws|Kawaiika[ ._-]?Raws|Koi[ ._-]?Raws|Lilith[ ._-]?Raws|LowPower[ ._-]?Raws|Nanako[ ._-]?Raws|NC[ ._-]?Raws|neko[ ._-]?raws|New[ ._-]?raws|Ohys[ ._-]?Raws|Pandoratv[ ._-]?Raws|Raws-Maji|Scryous[ ._-]?Raws|Seicher[ ._-]?Raws|Shiniori[ ._-]?Raws|ReinForce|Moozzi2|km)(?:\]|\b|$)' where "name" = 'Anime Raws' and "pattern" = '(?i)(?:^\[|(?<=-)|(?<=\[))(?:Beatrice-Raws|Daddy-Raws|Fumi-Raws|IrizaRaws|Kawaiika-Raws|Koi-Raws|Lilith-Raws|LowPower-Raws|NanakoRaws|NC-Raws|neko-raws|New-raws|Ohys-Raws|Pandoratv-Raws|Raws-Maji|Scryous-Raws|Seicher-Raws|Shiniori-Raws|AsukaRaws|ReinForce|Moozzi2|km)(?:\]|\b|$)';
-- --- END op 2428
